library(slidify)
library(knitr)
setwd("/Users/Huan/Dropbox/Courses/DataScientist/Capstone/Slidify")
author("Huan Fan")
slidify('index.Rmd')
browseURL('index.html')
publish_github('prophecy_cow','fanhuan')
